django_project/accounting/urls.py
from django.urls import path
from django.views.generic import TemplateView
from . import currency,chart_of_accounts,fiscal_year,type_of_bank,paymentvoucher,imprest



app_name = 'accounting'

urlpatterns = [
 #Currency start
    path('currency/',currency.currency,name='currency-list'),
    path('currency/new/',currency.add_currency,name='new-currency'),
    path('currency/<str:currenncy_id>/delete/',currency.delete_currency,name='delete-currency'),
    path('currency/upload/',currency.uploads_currency,name='uploads-currency'),
    path('currency/<str:currency_id>/edit/',currency.edit_currency,name='edit-currency'),
 #Currency End
 
 #Chart of Accounts Start
    path('chart-of-accounts/',chart_of_accounts.accountclass,name='accountclass-list'),
    path('chart-of-accounts/new/',chart_of_accounts.add_accountclass,name='new-accountclass'),
    path('chart-of-accounts/<str:accountclass_id>/edit/',chart_of_accounts.edit_accountclass,name='edit-accountclass'),
    path('chart-of-accounts/upload/',chart_of_accounts.uploads_accountclass,name='uploads-accountclass'),
    path('chart-of-accounts/<str:accountclass_id>/delete/',chart_of_accounts.delete_accountclass,name='delete-accountclass'),
    path('chart-of-accounts/<str:accountitem_id>/account-items/',chart_of_accounts.add_accountitem,name='add-accountitem'),
    path('chart-of-accounts/accountitem/<str:accountitem_id>/delete/',chart_of_accounts.delete_accountitem,name='delete-accountitem'),
    path('chart-of-accounts/accountitem/<str:accountitem_id>/edit/',chart_of_accounts.edit_accountitem,name='edit-accountitem'),
    path('chart-of-accounts/<str:accountitem_id>/account-subitems/',chart_of_accounts.add_accountsubitem,name='add-accountsubitem'),
    path('chart-of-accounts/<str:accountsubitem_id>/account-subitems/edit/',chart_of_accounts.edit_accountsubitem,name='edit-accountsubitem'),
    path('chart-of-accounts/<str:accountsubsubitem_id>/account-subsubitems/',chart_of_accounts.add_accountsubsubitem,name='add-accountsubsubitem'),
    path('chart-of-accounts/<str:accountsubsubitem_id>/account-subsubitems/edit/',chart_of_accounts.edit_accountsubsubitem,name='edit-accountsubsubitem'),
    path('chart-of-accounts/item/subiitem/subsubitem/<str:subsubitem_id>/change_status/',chart_of_accounts.change_subsubitemstatus,name='change-subsubitemstatus'),
#Chart of Accounts End

#Fiscal Start
    path('fiscalyear/',fiscal_year.fiscalyear,name='fiscalyear-list'),
    path('fiscalyear/new/',fiscal_year.add_fiscalyear,name='add-fiscalyear'),
    path('fiscalyear/<str:fiscalyear_id>/update/',fiscal_year.edit_fiscalyear,name='edit-fiscalyear'),
    path('fiscalyear/<str:fiscalyear_id>/delete/',fiscal_year.delete_fiscalyear,name='dellete-fiscalyear'),
    path('fiscalyear/<str:fiscalyear_id>/activate/',fiscal_year.activate_fiscalyear,name='activate-fiscalyear'),
    path('fiscalyear/<str:fiscalyear_id>/deactivate/',fiscal_year.deactivate_fiscalyear,name='deactivate-fiscalyear'),
#End Fiscal Year

#Bank Acoounts Type Start
   path('bank/acoounts/type/',type_of_bank.banktype,name='banktype-list'),
   path('bank/acoounts/type/new/',type_of_bank.add_banktype,name='new-banktype'),
   path('bank/acoounts/type/<str:banktypeid_id>/update/',type_of_bank.edit_banktype,name='edit-banktype'),
   path('bank/acoounts/type/<str:banktypeid_id>/delete/',type_of_bank.delete_banktype,name='delete-banktype'),
   path('bank/acoounts/type/upload/',type_of_bank.banktype_upload,name='upload-banktype'),
   path('assign/bank/accounts/type/',type_of_bank.assign_banktype,name='assign-banktype'),
#Bank Acoounts Type End

#Payment Voucher Start

   path('paymentvoucher/',paymentvoucher.manage_paymentvouchers,name='paymentvoucher-list'),
   path('paymentvoucher/ia/',paymentvoucher.ia_paymentvouchers,name='ia-list'),
   path('paymentvoucher/payables/list/',paymentvoucher.payables,name='payables'),
   path('paymentvoucher/pending/',paymentvoucher.pending_paymentvouchers,name='pending-paymentvoucher-list'),
   path('paymentvoucher/authorised/',paymentvoucher.approve_paymentvouchers,name='authorised-paymentvoucher-list'),
   path('paymentvoucher/approved/',paymentvoucher.authorisedpassed_paymentvouchers,name='authorisedandpay-paymentvoucher-list'),
   path('paymentvoucher/cheque/entry/list/',paymentvoucher.checknumber_paymentvouchers,name='chequeno-paymentvoucher-list'),
   path('paymentvoucher/all/',paymentvoucher.all_paymentvouchers,name='all-paymentvoucher-list'),
   path('paymentvoucher/<str:document_id>/new/',paymentvoucher.add_pv,name='new-pv'),
   path('paymentvoucher/new/without-document/',paymentvoucher.add_pv_without_doc,name='new-no-doc-pv'),
   path('paymentvoucher/new/<str:pv_id>/detail/',paymentvoucher.add_pv_detail,name='add-deatil-pv'),
   path('paymentvoucher/<str:pv_id>/detail/',paymentvoucher.pv_detail,name='pv-detail'),
   path('paymentvoucher/<str:pv_id>/update/',paymentvoucher.update_pv,name='edit-update_pv'),
   path('paymentvoucher/detail/item/<str:pvitem_id>/delete/',paymentvoucher.delete_pvitem,name='delete_pvitem'),
   path('paymentvoucher/<str:pv_id>/approve/',paymentvoucher.change_pv_status,name='change-pv-status'),
   path('paymentvoucher/<str:pv_id>/cheque-number/',paymentvoucher.add_cheque_no,name='add-cheque-no'),
   path('paymentvoucher/<str:pv_id>/check-eligibility/',paymentvoucher.check_pv_eligibility,name='check-pv-eligibility'),
   path('paymentvoucher/<str:ia_id>/internal/audit/ledger/',paymentvoucher.ia_detail,name='ia-detail'),
   path('paymentvoucher/detail/<str:attachemnt_id>/attachment/view/',paymentvoucher.view_pvattachment,name='view-pvattachment'),
   path('paymentvoucher/detail/<str:pv_id>/attachment/new/',paymentvoucher.add_pv_attachment,name='add-pv-attachment'),
   path('paymentvoucher/attachemnt/<str:item_id>/remove/', paymentvoucher.remove_pvattachemnt,name='remove-pvattachemnt'),
   path('paymentvoucher/deatil/<str:pv_id>/document/',paymentvoucher.view_pvdocument_detail,name='view-pvdocument-detail'),
   path('paymentvoucher/<str:pv_id>/correction/',paymentvoucher.sendbackto_ia_pvattachemnt,name='sendbackto-ia-pvattachemnt'),
   path('paymentvoucher/<str:pv_id>/document/attachment/<str:attachment_id>/view/',paymentvoucher.view_pvdocattachment,name='view-pvdocattachment'),
   path('paymentvoucher/<str:pv_id>/nofity/payee/',paymentvoucher.notifypayee,name='notifypayee'),
   path('paymentvoucher/<str:pv_id>/cheque/confirm/',paymentvoucher.comfirm_checknumber,name='comfirm-checknumber'),
   path('paymentvoucher/<str:pv_id>/beneficiaries/',paymentvoucher.pull_beneficiaries,name='pull-beneficiaries'),
   path('paymentvoucher/<str:pv_id>/add/beneficiaries/',paymentvoucher.pv_beneficiary_upload,name='pv-beneficiary-upload'),
   path('paymentvoucher/<str:pv_id>/beneficiaries/list/',paymentvoucher.list_pv_beneficiary,name='list-pv-beneficiary'),
   path('paymentvoucher/beneficiary/list/<str:item_id>/comfirm/',paymentvoucher.comfirm_code,name='comfirm-code'),
   path('paymentvoucher/beneficiary/list/<str:item_id>/comfirm/code/resend/',paymentvoucher.resend_code,name='resend-code'),
   path('paymentvoucher/beneficiarylist/<str:item_id>/pay/',paymentvoucher.make_payment,name='make-payment'),
   
#Payment Voucher End

#Imprest Start
   path('imprest/',imprest.manage_imprest,name='manage-imprest'),
   path('imprest/pending/',imprest.pending_imprest,name='pending-imprest'),
   path('imprest/approved/',imprest.approved_imprest,name='approved-imprest'),
   path('imprest/certified/',imprest.certified_imprest,name='certified-imprest'),
   path('imprest/retire/',imprest.retire_imprest,name='retire-imprest'),
   path('imprest/new/',imprest.add_imprest,name='add-imprest'),
   path('imprest/<str:imprest_id>/',imprest.imprest_detail,name='imprest-detail'),
   path('imprest/<str:imprest_id>/update/',imprest.edit_imprest,name='edit-imprest'),
   path('imprest/<str:imprest_id>/approve/',imprest.imprest_change_status,name='imprest-change-status'),
   path('imprest/<str:imprest_id>/close/',imprest.notifyhod,name='imprest-notifyhod-close'),
   path('imprest/<str:imprest_id>/actualexpense/',imprest.add_imprest_expense,name='add-imprest-expense')

#Imprest End 
]

django_project/dms/urls.py
from django.urls import path
from django.views.generic import TemplateView
from . import documents



app_name = 'dms'

urlpatterns = [
    #folder start
    path('filemanager/',documents.filemanager,name='filemanager-list'),
    path('filemanager/create-folder/',documents.add_folder,name='create-folder'),
    path('filemanager/folder/<str:folder_id>/pin_folder',documents.pin_folder,name='pin-folder'),
    path('filemanager/folder/<str:folder_id>/unpin_folder',documents.unpin_folder,name='unpin-folder'),
    path('filemanager/folder/<str:folder_id>/update/',documents.edit_folder,name='edit-folder'),
    path('filemanager/files/new/',documents.add_file,name='new-file'),
    path('filemanager/files/<str:file_id>/update/',documents.edit_file,name='edit-file'),
    
    path('filemanager/folder/<str:folder_id>/detail',documents.files,name='folder-detail'),
    path('filemanager/folder/file/<str:file_id>/generate/',documents.add_document_detail,name='add-document_detail'),
    path('filemanager/folder/file/<str:file_id>/edit/',documents.edit_document_detail,name='edit-document_detail'),
    path('filemanager/folder/document/paragraph/<str:item_id>/item/remove/',documents.remove_document_item,name='remove-document_item'),
    path('filemanager/folder/document/<str:document_id>/draft/',documents.save_as_draft,name='save-as_draft'),
    path('filemanager/folder/document/<str:document_id>/approve/',documents.sendpprove_document,name='sendpprove-document'),
    path('filemanager/files/<str:file_id>/currency/',documents.add_document_currency,name='add-document_currency'),
    path('filemanager/files/<str:file_id>/currency/edit/',documents.edit_document_currency,name='edit-document_currency'),
    path('filemanager/folder/<str:file_id>/dudget/',documents.add_document_budget,name='add-document_budget'),
    path('filemanager/folder/document/dudget/<str:item_id>/item/remove/',documents.remove_budget_item,name='remove-budget_item'),
    # path('filemanager/folder/file/<str:file_id>/generate/',documents.add_document_detail,name='add-document_detail')
    path('filemanager/folder/document/document/<str:document_id>/attachement/',documents.add_attachment,name='add-attachment'),
    path('filemanager/folder/document/document/<str:item_id>/attachement/remove/',documents.remove_attachemnt,name='remove-attachemnt'),
    path('filemanager/folder/document/document/<str:document_id>/attachement/detail/',documents.view_attachment,name='view-attachment'),
    path('filemanager/folder/document/document/<str:document_id>/minute/',documents.add_munites,name='add-munites'),

    path('filemanager/folder/document/<str:document_id>/save/',documents.save_to_send,name='save-to-send'),
    path('filemanager/folder/document/<str:file_id>/detail/',documents.view_document_detail,name='view-document_detail'),
    path('filemanager/folder/document/<str:document_id>/return_or_cancel/',documents.return_document,name='return-document'),
    path('filemanager/folder/document/<str:file_id>/approved_amount/',documents.add_approved_amount,name='add-approved_amount'),
    path('filemanager/file/<str:file_id>/beneficiary/', documents.document_beneficiary_upload,name='document-beneficiary-upload'),
    path('filemanager/file/<str:file_id>/pull_low_stock/',documents.pull_low_stock_product,name='pull-product'),
    


    
    #Folder end
    
]

django_project/erpproject/urls.py
from django.contrib import admin
from django.urls import path,include
from erpproject import views

from django.contrib.auth.decorators import login_required
from django.views.generic import TemplateView

from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import handler404


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.DashboardView,name='dashboard'), 
    path('authentication/', include('authentication.urls', namespace='authentication')), 
    path('inventory/', include('inventory.urls', namespace='inventory')), 
    path('company/', include('company.urls', namespace='company')), 
    path('accounting/',include('accounting.urls', namespace='accounting')),
    path('dms/',include('dms.urls',namespace='dms')),
    path('supplychain/',include('supply_chain.urls',namespace='supplychain')),
    path('purchaseorder/',include('purchase_order.urls',namespace='purchaseorder')),
    path('fixedassets/',include('fixedassets.urls',namespace='fixedassets')),
    path('helpdesk/',include('helpdesk.urls',namespace='helpdesk')),
]

handler404 = 'authentication.auth.error_404_view'
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django_project/templates/accounting/banktype/bank.html
{% extends 'partials/accounting/base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block extra_css %}
    
    <!-- DataTables -->
    <link href="{% static 'libs/datatables.net-bs4/css/dataTables.bootstrap4.min.css' %}" rel="stylesheet" type="text/css" />
    <link href="{% static 'libs/datatables.net-buttons-bs4/css/buttons.bootstrap4.min.css' %}" rel="stylesheet" type="text/css" />

    <!-- Responsive datatable examples -->
    <link href="{% static 'libs/datatables.net-responsive-bs4/css/responsive.bootstrap4.min.css' %}" rel="stylesheet" type="text/css" />  
    <link href="{% static 'libs/bootstrap-datepicker/dist/css/bootstrap-datepicker.min.css' %}" rel="stylesheet" type="text/css">
    {% comment %} <link href="{% static 'libs/select2/css/select2.min.css' %}" rel="stylesheet" type="text/css" /> {% endcomment %}
    <link href="{% static 'css/bootstrap.min.css' %}" id="bootstrap-style" rel="stylesheet" type="text/css" />
    <!-- Icons Css -->
    <link href="{% static 'css/icons.min.css' %}" rel="stylesheet" type="text/css" />
    <!-- App Css-->
    <link href="{% static 'css/app.min.css' %}" id="app-style" rel="stylesheet" type="text/css" />

{% endblock %}
{% block contents %}
<div class="row">
    <div class="col-lg-12">
        {% #card title="List Of Bank Accounts Type" %}
        
        <div class="table-responsive">
            {% if perms.accounting.custom_create_pv %}
                <div class="flex-shrink-0 d-flex justify-content-end mb-1" >
                    <a href="{% url 'accounting:new-banktype' %}" class="btn btn-primary m-2 ">Add Bank Account Type</a>
                    <a href="{% url 'accounting:assign-banktype' %}" class="btn btn-warning m-2 ">Assign Bank Type To Sub Devisions</a>
                    <a href="{% url 'accounting:upload-banktype' %}" class="btn btn-success  ml-2 mt-2 mb-2">Bank Acoount Type</a>
                </div>
            {% endif %}
            {% #table %}
                {% #thead %}
                    {% #tr name ="headrow" %}
                        {% #th name ="headid" %}ID{% /th %}
                        {% #th name ="headName" %}Name{% /th %}
                        {% if perms.accounting.custom_create_pv  %}
                            {% #th name ="headAction" %} Action {% /th %}
                        {% endif %}
                    {% /tr %}
                {% /thead%}
                {% #tbody %}
                    {% for data in bank_list  %}
                        {% #tr name ="bodyrow" %}
                            {% #td name ="groupid" %}{{data.id}}{% /td %}
                            {% #td name ="groupname" %}{{data.name}}{% /td %}
                            {% if perms.accounting.custom_create_pv  %}
                                {% #td name ="bankaction" %}
                                
                                    {% #actions name ="bankedit" %}
                                    
                                            <li data-bs-toggle="tooltip" data-bs-placement="top" data-bs-title="Edit">
                                                <a href="{% url 'accounting:edit-banktype' data.id %}" class="btn btn-sm btn-soft-info"><i class="mdi mdi-pencil-outline"></i></a>
                                            </li>
                                            
                                            {% if perms.accounting.custom_delete_pv %}
                                                <li data-bs-toggle="tooltip" data-bs-placement="top" data-bs-title="Delete">
                                                    
                                                    <a href="#delete_link" id="delete-record" data-record-id="{{ data.id }}" data-bs-toggle="modal" class="delete-record btn btn-sm btn-soft-danger" data-target="#jobDelete"><i class="mdi mdi-delete-outline"></i></a>
                                                </li>
                                            {% endif %}
                                                
                                    {% /actions %}
                                
                                {% /td %}
                            {% endif %}
                        {% /tr %}
                    {% endfor %}
                {% /tbody %}
            {% /table %}
           
            <!-- end table -->
        </div>
        {% /card %}
        <!--end card-->
       
</div>

{% endblock %}

{% block extra_content %}  
    {% #comfirmation   %}
        {% #avatar %}
            <i class="mdi mdi-trash-can-outline"></i>     
        {% /avatar %} 
        {% #comfirmationtext %}
            Are you sure you want to permanently delete this Bank Accounts Type
        {% /comfirmationtext %} 

        {% #comfirmation_footer %}
            <a href="#" id ="deleteModalAnchor" class="btn btn-danger">Delete Now</a>
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        {% /comfirmation_footer %}     
    {% /comfirmation %}
 


{% endblock %}

{% block extra_javascript %}

     <!-- Required datatable js -->
     <script src="{% static 'libs/datatables.net/js/jquery.dataTables.min.js' %}"></script>
     <script src="{% static 'libs/datatables.net-bs4/js/dataTables.bootstrap4.min.js' %}"></script>
     <script src="{% static 'libs/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js' %}"></script>
     <!-- Buttons examples -->
     <script src="{% static 'libs/datatables.net-buttons/js/dataTables.buttons.min.js' %}"></script>
     <script src="{% static 'libs/datatables.net-buttons-bs4/js/buttons.bootstrap4.min.js' %}"></script>
     <script src="{% static 'libs/jszip/dist/jszip.min.js' %}"></script>
     <script src="{% static 'libs/pdfmake/build/pdfmake.min.js' %}"></script>
     <script src="{% static 'libs/pdfmake/build/vfs_fonts.js' %}"></script>
     <script src="{% static 'libs/datatables.net-buttons/js/buttons.html5.min.js' %}"></script>
     <script src="{% static 'libs/datatables.net-buttons/js/buttons.print.min.js' %}"></script>
     <script src="{% static 'libs/datatables.net-buttons/js/buttons.colVis.min.js' %}"></script>
     
     <!-- Responsive examples -->
     <script src="{% static 'libs/datatables.net-responsive/js/dataTables.responsive.min.js' %}"></script>
     <script src="{% static 'libs/datatables.net-responsive-bs4/js/responsive.bootstrap4.min.js' %}"></script>

     <!-- Datatable init js -->
     <script src="{% static 'js/pages/datatables.init.js' %}"></script>
     
    {% comment %} <script src="{% static 'js/auto_modal.js' %}"></script> {% endcomment %}

     <script>
        document.addEventListener("DOMContentLoaded", function() {
            var deleteAnchors = document.getElementsByClassName("delete-record");
            var deleteModalAnchor = document.getElementById("deleteModalAnchor");
            Array.from(deleteAnchors).forEach(function(anchor) {
              anchor.addEventListener("click", function(event) {
                event.preventDefault();
                var recordId = this.getAttribute("data-record-id"); 
                deleteModalAnchor.setAttribute("data-record-id", recordId);
                deleteModalAnchor.setAttribute("href", "/accounting/bank/acoounts/type/" + recordId + "/delete/");
                deleteModalAnchor.style.display = "block";
              });
            });
          });
     </script>

{% endblock %}

django_project/templates/accounting/banktype/create-banktype.html
{% extends 'partials/accounting/base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block extra_css %}
    <link href="{% static 'css/bootstrap.min.css' %}" id="bootstrap-style" rel="stylesheet" type="text/css" />
    <!-- Icons Css -->
    <link href="{% static 'css/icons.min.css' %}" rel="stylesheet" type="text/css" />
    <!-- App Css-->
    <link href="{% static 'css/app.min.css' %}" id="app-style" rel="stylesheet" type="text/css" />

{% endblock %}
{% block contents %}
<div class="row">
    <div class="col-lg-12">
       {% #card title="Bank Acoount Type" %}
       
            <div class="m-3">
                {% #form %}
                    {% csrf_token %}
                    <div class=" row mb-3">
                        
                            <div class="col-6 col-sm-12 col-md-6">
                                <label for="formrow-firstname-input" class="form-label">Bank Account Type Name</label>
                                {{form.name|as_crispy_field}}
                            </div>
                      
                    </div>
                    
                    <div class="mb-2">
                        {% var class=class|default:"btn btn-primary w-md" %}
                        {% #button {% attrs class %} Save {% /button %}
                    </div>
                {% /form %}
            
            </div>
        {% /card %}
        <!--end card-->
       
</div>

{% endblock %}