django_project/dms/urls.py
from django.urls import path
from django.views.generic import TemplateView
from . import documents



app_name = 'dms'

urlpatterns = [
    #folder start
    path('filemanager/',documents.filemanager,name='filemanager-list'),
    path('filemanager/create-folder/',documents.add_folder,name='create-folder'),
    path('filemanager/folder/<str:folder_id>/pin_folder',documents.pin_folder,name='pin-folder'),
    path('filemanager/folder/<str:folder_id>/unpin_folder',documents.unpin_folder,name='unpin-folder'),
    path('filemanager/folder/<str:folder_id>/update/',documents.edit_folder,name='edit-folder'),
    path('filemanager/files/new/',documents.add_file,name='new-file'),
    path('filemanager/files/<str:file_id>/update/',documents.edit_file,name='edit-file'),
    
    path('filemanager/folder/<str:folder_id>/detail',documents.files,name='folder-detail'),
    path('filemanager/folder/file/<str:file_id>/generate/',documents.add_document_detail,name='add-document_detail'),
    path('filemanager/folder/file/<str:file_id>/edit/',documents.edit_document_detail,name='edit-document_detail'),
    path('filemanager/folder/document/paragraph/<str:item_id>/item/remove/',documents.remove_document_item,name='remove-document_item'),
    path('filemanager/folder/document/<str:document_id>/draft/',documents.save_as_draft,name='save-as_draft'),
    path('filemanager/folder/document/<str:document_id>/approve/',documents.sendpprove_document,name='sendpprove-document'),
    path('filemanager/files/<str:file_id>/currency/',documents.add_document_currency,name='add-document_currency'),
    path('filemanager/files/<str:file_id>/currency/edit/',documents.edit_document_currency,name='edit-document_currency'),
    path('filemanager/folder/<str:file_id>/dudget/',documents.add_document_budget,name='add-document_budget'),
    path('filemanager/folder/document/dudget/<str:item_id>/item/remove/',documents.remove_budget_item,name='remove-budget_item'),
    # path('filemanager/folder/file/<str:file_id>/generate/',documents.add_document_detail,name='add-document_detail')
    path('filemanager/folder/document/document/<str:document_id>/attachement/',documents.add_attachment,name='add-attachment'),
    path('filemanager/folder/document/document/<str:item_id>/attachement/remove/',documents.remove_attachemnt,name='remove-attachemnt'),
    path('filemanager/folder/document/document/<str:document_id>/attachement/detail/',documents.view_attachment,name='view-attachment'),
    path('filemanager/folder/document/document/<str:document_id>/minute/',documents.add_munites,name='add-munites'),

    path('filemanager/folder/document/<str:document_id>/save/',documents.save_to_send,name='save-to-send'),
    path('filemanager/folder/document/<str:file_id>/detail/',documents.view_document_detail,name='view-document_detail'),
    path('filemanager/folder/document/<str:document_id>/return_or_cancel/',documents.return_document,name='return-document'),
    path('filemanager/folder/document/<str:file_id>/approved_amount/',documents.add_approved_amount,name='add-approved_amount'),
    path('filemanager/file/<str:file_id>/beneficiary/', documents.document_beneficiary_upload,name='document-beneficiary-upload'),
    path('filemanager/file/<str:file_id>/pull_low_stock/',documents.pull_low_stock_product,name='pull-product'),
    


    
    #Folder end
    
]

django_project/erpproject/urls.py
from django.contrib import admin
from django.urls import path,include
from erpproject import views

from django.contrib.auth.decorators import login_required
from django.views.generic import TemplateView

from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import handler404


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.DashboardView,name='dashboard'), 
    path('authentication/', include('authentication.urls', namespace='authentication')), 
    path('inventory/', include('inventory.urls', namespace='inventory')), 
    path('company/', include('company.urls', namespace='company')), 
    path('accounting/',include('accounting.urls', namespace='accounting')),
    path('dms/',include('dms.urls',namespace='dms')),
    path('supplychain/',include('supply_chain.urls',namespace='supplychain')),
    path('purchaseorder/',include('purchase_order.urls',namespace='purchaseorder')),
    path('fixedassets/',include('fixedassets.urls',namespace='fixedassets')),
    path('helpdesk/',include('helpdesk.urls',namespace='helpdesk')),
]

handler404 = 'authentication.auth.error_404_view'
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django_project/fixedassets/urls.py
from django.urls import path
from .import classification,accountingrecognition,ipsascategory,location,sourceoffunding,gfscategory,subcategory,methodofacquisition,assets

app_name = 'fixedassets'

urlpatterns = [
    #Classification Start
    path('classification/',classification.classification,name='classification-list'),
    path('classification/add/',classification.add_classification,name='new-classification'),
    path('classification/<str:classification_id>/update/',classification.edit_classification,name='edit-classification'),
    path('classification/<str:classification_id>/delete/',classification.delete_classification,name='delete-classification'),
    path('classification/upload/',classification.classification_upload,name='upload-classification'),
    #Classification End

    #Accounting Recognition Start
    path('accountingrecognition/',accountingrecognition.recognition,name='recognition-list'),
    path('accountingrecognition/add/',accountingrecognition.add_recognition,name='new-recognition'),
    path('accountingrecognition/<str:recognition_id>/update/',accountingrecognition.edit_recognition,name='edit-recognition'),
    path('accountingrecognition/<str:recognition_id>/delete/',accountingrecognition.delete_recognition,name='delete-recognition'),
    path('accountingrecognition/upload/',accountingrecognition.recognition_upload,name='upload-recognition'),
    #Accounting Recognition End

    #GFS Category Start
    path('gfscategory/',gfscategory.gfscategory,name='gfscategory-list'),
    path('gfscategory/add/',gfscategory.add_gfscategory,name='new-gfscategory'),
    path('gfscategory/<str:gfscategory_id>/update/',gfscategory.edit_gfscategory,name='edit-gfscategory'),
    path('gfscategory/<str:gfscategory_id>/delete/',gfscategory.delete_gfscategory,name='delete-gfscategory'),
    path('gfscategory/upload/',gfscategory.gfscategory_upload,name='upload-gfscategory'),
    #GFS Category End

    #Ipsas Category Start
    path('ipsascategory/',ipsascategory.ipsascategory,name='ipsascategory-list'),
    path('ipsascategory/add/',ipsascategory.add_ipsascategory,name='new-ipsascategory'),
    path('ipsascategory/<str:ipsascategory_id>/update/',ipsascategory.edit_ipsascategory,name='edit-ipsascategory'),
    path('ipsascategory/<str:ipsascategory_id>/delete/',ipsascategory.delete_ipsascategory,name='delete-ipsascategory'),
    path('ipsascategory/upload/',ipsascategory.ipsascategory_upload,name='upload-ipsascategory'),
    #Ipsas Category End

    #Location Start
    path('location/',location.location,name='location-list'),
    path('location/add/',location.add_location,name='new-location'),
    path('location/<str:location_id>/update/',location.edit_location,name='edit-location'),
    path('location/<str:location_id>/delete/',location.delete_location,name='delete-location'),
    path('location/upload/',location.location_upload,name='upload-location'),
    #Location End

    #Funding Start
    path('funding/',sourceoffunding.funding,name='funding-list'),
    path('funding/add/',sourceoffunding.add_funding,name='new-funding'),
    path('funding/<str:funding_id>/update/',sourceoffunding.edit_funding,name='edit-funding'),
    path('funding/<str:funding_id>/delete/',sourceoffunding.delete_funding,name='delete-funding'),
    path('funding/upload/',sourceoffunding.funding_upload,name='upload-funding'),
    #Funding End

    #Sub Category Start
    path('subcategory/',subcategory.subcategory,name='subcategory-list'),
    path('subcategory/add/',subcategory.add_subcategory,name='new-subcategory'),
    path('subcategory/<str:subcategory_id>/update/',subcategory.edit_subcategory,name='edit-subcategory'),
    path('subcategory/<str:subcategory_id>/delete/',subcategory.delete_subcategory,name='delete-subcategory'),
    path('subcategory/upload/',subcategory.subcategory_upload,name='upload-subcategory'),
    #Sub Category End

    #Method of Acquisition Start
    path('methodofacquisition/',methodofacquisition.methodofacquisition,name='methodofacquisition-list'),
    path('methodofacquisition/add/',methodofacquisition.add_methodofacquisition,name='new-methodofacquisition'),
    path('methodofacquisition/<str:methodofacquisition_id>/update/',methodofacquisition.edit_methodofacquisition,name='edit-methodofacquisition'),
    path('methodofacquisition/<str:methodofacquisition_id>/delete/',methodofacquisition.delete_methodofacquisition,name='delete-methodofacquisition'),
    path('methodofacquisition/upload/',methodofacquisition.methodofacquisition_upload,name='upload-methodofacquisition'),
    #Method of Acquisition End

    #Assets Start
    path('assets/',assets.assets,name='asset-list'),
    path('assets/selectclassification/',assets.add_selectclassification,name='select-classification'),
    path('assets/reportselect/',assets.report_selectclassification,name='report-selectclassification'),
    path('assets/reportselect/<str:assetclassification>/',assets.export_excel,name='export-excel'),
    path('assets/<str:formclassification>/add/',assets.add_assets,name='new-asset'),
    path('assets/load_subcategory/',assets.load_subcategory,name="load-subcategory"),
    path('assets/load_user/',assets.load_user,name="load_user"),
    path('assets/<str:asset_id>/update/',assets.edit_assets,name='edit-assets'),
    path('assets/<str:asset_id>/delete/',assets.delete_asset,name='delete-assets'),
    path('assets/<str:asset_id>/assign/',assets.assigned_assets,name='assigned-assets'),
    path('assets/<str:asset_id>/view_assets/',assets.view_assets,name='detail-assets'),
    path('assets/<str:assign_id>/return/',assets.return_assets,name='returned-assets'),
    path('assets/depreciation/',assets.depreciation,name='depreciation-list'),
    path('assets/depreciation/new/',assets.run_depreciation,name='new-depreciation'),
    path('assets/depreciaition/<depreciation_id>',assets.view_depreciation,name='detail-depreciation'),
    path('assets/duereevaluation',assets.reevaluation,name='reevaluation-list'),
    path('assets/<str:asset_id>/evaluate/',assets.reevaluate_asset,name='reevaluate-asset'),
    path('assets/disposal/',assets.disposal,name='disposal-list'),
    path('assets/<str:asset_id>/disposal/',assets.disposal_asset,name='dispose-asset'),
    path('assets/dashboard/',assets.assetdashboard,name='assetdashboard'),


    
    # path('methodofacquisition/<str:methodofacquisition_id>/delete/',methodofacquisition.delete_methodofacquisition,name='delete-methodofacquisition'),
    # path('methodofacquisition/upload/',methodofacquisition.methodofacquisition_upload,name='upload-methodofacquisition'),
    #MAssets End
]

django_project/templates/fixedassets/assets/depreciation/depreciation.html
{% extends 'partials/fixedassets/fixedassetsbase.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% load humanize %}

{% block extra_css %}
    
    <!-- DataTables -->
    <link href="{% static 'libs/datatables.net-bs4/css/dataTables.bootstrap4.min.css' %}" rel="stylesheet" type="text/css" />
    <link href="{% static 'libs/datatables.net-buttons-bs4/css/buttons.bootstrap4.min.css' %}" rel="stylesheet" type="text/css" />

    <!-- Responsive datatable examples -->
    <link href="{% static 'libs/datatables.net-responsive-bs4/css/responsive.bootstrap4.min.css' %}" rel="stylesheet" type="text/css" />  
    <link href="{% static 'libs/bootstrap-datepicker/dist/css/bootstrap-datepicker.min.css' %}" rel="stylesheet" type="text/css">
    {% comment %} <link href="{% static 'libs/select2/css/select2.min.css' %}" rel="stylesheet" type="text/css" /> {% endcomment %}
    <link href="{% static 'css/bootstrap.min.css' %}" id="bootstrap-style" rel="stylesheet" type="text/css" />
    <!-- Icons Css -->
    <link href="{% static 'css/icons.min.css' %}" rel="stylesheet" type="text/css" />
    <!-- App Css-->
    <link href="{% static 'css/app.min.css' %}" id="app-style" rel="stylesheet" type="text/css" />

{% endblock %}
{% block contents %}
<div class="row">
    <div class="col-lg-4 col-md-6 col-sm-12">
        <!-- GHC {{ asset.costbf|floatformat:2|intcomma }} -->
        {% #stats-card  name = "totalusers" %}
            {% #stats-card-text name="totaltext" %}
                <p class="text-muted mb-2">Current Depreciation year</p>
                <h5 class="mb-0">
                    
                    {% if current_depreciation %}
                        {{current_depreciation.accountingyear.period}}
                    {% else %}
                        No Current Year
                    {% endif %}
                        
                    <!-- GHC 0|floatformat:2|intcomm -->
                </h5>
            {% /stats-card-text %}
            {% #stats-card-avatar  name="totalav"%}
                    <i class="bx bxs-book-bookmark"></i> 
            {% /stats-card-avatar %}
        {% /stats-card %}
    </div>
    <div class="col-lg-4 col-md-6 col-sm-12">
        {% #stats-card name = "totalactive" %}
            {% #stats-card-text name="activetest" %}
                <p class="text-muted mb-2">Current Depreciation</p>
                <h5 class="mb-0">
                    {% if current_depreciation %}
                        GHC {{current_depreciation.depreciationvalue|floatformat:2|intcomma}}
                    {% else %}
                        GHC 0.00
                    {% endif %}
                    
                </h5>
            {% /stats-card-text %}
            {% #stats-card-avatar name="activeav" %}
                    <i class="bx bxs-note"></i> 
            {% /stats-card-avatar %}
        {% /stats-card %}
    </div>
    <div class="col-lg-4 col-md-6 col-sm-12">
        {% #stats-card  name = "totalinactive" %}
            {% #stats-card-text name="inactivetest" %}
                <p class="text-muted mb-2">Accumulated Depreciation</p>
                <h5 class="mb-0">
                    
                    {% if accumulated_depreciation %}
                      GHC {{accumulated_depreciation.cc|floatformat:2|intcomma}}
                    {% else %}
                      GHC 0.00
                        
                    {% endif %}
                  
                </h5>
            {% /stats-card-text %}
            {% #stats-card-avatar  name="inactiveav"%}
                    <i class="bx bxs-message-square-dots"></i> 
            {% /stats-card-avatar %}
        {% /stats-card %}
    </div>
</div>
<div class="row">
    <div class="col-lg-12">
        {% #card title="List Of Depreciation" %}
        
        <div class="table-responsive">
            {% if perms.fixedassets.custom_run_depreciation_on_fixed %}
                <div class="flex-shrink-0 d-flex justify-content-end mb-1" >
                    <a href="{% url 'fixedassets:new-depreciation' %}" class="btn btn-primary m-2 ">Run Depreciation</a>
                    
                </div>
            {% endif %}
            {% #table %}
                {% #thead %}
                    {% #tr name ="headrow" %}
                        {% #th name ="headid" %}ID{% /th %}
                        {% #th name ="headName" %}Accounting Period{% /th %}
                        {% #th name ="headName" %}Depreciation Value{% /th %}
                        {% #th name ="headName" %}Status{% /th %}

                        
                        {% #th name ="headAction" %} Action {% /th %}
                        
                    {% /tr %}
                {% /thead%}
                {% #tbody %}
                    {% for data in depreciation_list  %}
                        {% #tr name ="bodyrow" %}
                            {% #td name ="groupid" %}{{data.id}}{% /td %}
                            {% #td name ="groupname" %}{{data.accountingyear.period}}{% /td %}
                            {% #td name ="groupname" %}GHC {{data.depreciationvalue|floatformat:2|intcomma}}{% /td %}
                            {% #td name ="groupname" %}
                                {% if data.status == 'In Progress' %}
                                    <span class="badge bg-danger">{{data.status}}</span>
                                {% else %}
                                    <span class="badge bg-primary">{{data.status}}</span>
                                    
                                {% endif %}
                            {% /td %}
                            
                            {% if perms.fixedassets.custom_run_depreciation_on_fixed %}
                                {% #td name ="groupaction" %}
                                
                                    {% #actions name ="groupedit" %}
                                  
                                        
                                        <li data-bs-toggle="tooltip" data-bs-placement="top" data-bs-title="Depreciation Details">
                                            <a href="{% url 'fixedassets:detail-depreciation' data.id %}" class="btn btn-sm btn-soft-primary"><i class="mdi mdi-eye-outline"></i></a>
                                        </li>
                                    
                                       
                                    
                                    {% /actions %}
                                
                                {% /td %}
                            {% endif %}
                        {% /tr %}
                    {% endfor %}
                {% /tbody %}
            {% /table %}
           
            <!-- end table -->
        </div>
        {% /card %}
        <!--end card-->
       
</div>

{% endblock %}

<!-- {% block extra_content %}  
    {% #comfirmation   %}
        {% #avatar %}
            <i class="mdi mdi-trash-can-outline"></i>     
        {% /avatar %} 
        {% #comfirmationtext %}
            Are you sure you want to permanently delete this Assets.
        {% /comfirmationtext %} 

        {% #comfirmation_footer %}
            <a href="#" id ="deleteModalAnchor" class="btn btn-danger">Delete Now</a>
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        {% /comfirmation_footer %}     
    {% /comfirmation %}
 


{% endblock %} -->

{% block extra_javascript %}

     <!-- Required datatable js -->
     <script src="{% static 'libs/datatables.net/js/jquery.dataTables.min.js' %}"></script>
     <script src="{% static 'libs/datatables.net-bs4/js/dataTables.bootstrap4.min.js' %}"></script>
     <script src="{% static 'libs/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js' %}"></script>
     <!-- Buttons examples -->
     <script src="{% static 'libs/datatables.net-buttons/js/dataTables.buttons.min.js' %}"></script>
     <script src="{% static 'libs/datatables.net-buttons-bs4/js/buttons.bootstrap4.min.js' %}"></script>
     <script src="{% static 'libs/jszip/dist/jszip.min.js' %}"></script>
     <script src="{% static 'libs/pdfmake/build/pdfmake.min.js' %}"></script>
     <script src="{% static 'libs/pdfmake/build/vfs_fonts.js' %}"></script>
     <script src="{% static 'libs/datatables.net-buttons/js/buttons.html5.min.js' %}"></script>
     <script src="{% static 'libs/datatables.net-buttons/js/buttons.print.min.js' %}"></script>
     <script src="{% static 'libs/datatables.net-buttons/js/buttons.colVis.min.js' %}"></script>
     
     <!-- Responsive examples -->
     <script src="{% static 'libs/datatables.net-responsive/js/dataTables.responsive.min.js' %}"></script>
     <script src="{% static 'libs/datatables.net-responsive-bs4/js/responsive.bootstrap4.min.js' %}"></script>

     <!-- Datatable init js -->
     <script src="{% static 'js/pages/datatables.init.js' %}"></script>
     
    {% comment %} <script src="{% static 'js/auto_modal.js' %}"></script> {% endcomment %}

     <!-- <script>
        document.addEventListener("DOMContentLoaded", function() {
            var deleteAnchors = document.getElementsByClassName("delete-record");
            var deleteModalAnchor = document.getElementById("deleteModalAnchor");
            Array.from(deleteAnchors).forEach(function(anchor) {
              anchor.addEventListener("click", function(event) {
                event.preventDefault();
                var recordId = this.getAttribute("data-record-id"); 
                deleteModalAnchor.setAttribute("data-record-id", recordId);
                deleteModalAnchor.setAttribute("href", "/fixedassets/assets/" + recordId + "/delete/");
                deleteModalAnchor.style.display = "block";
              });
            });
          });
     </script> -->

{% endblock %}

django_project/templates/fixedassets/assets/depreciation/view-depreciation.html
{% extends 'partials/fixedassets/fixedassetsbase.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% load humanize %}

{% block extra_css %}
    
    <!-- DataTables -->
    <link href="{% static 'libs/datatables.net-bs4/css/dataTables.bootstrap4.min.css' %}" rel="stylesheet" type="text/css" />
    <link href="{% static 'libs/datatables.net-buttons-bs4/css/buttons.bootstrap4.min.css' %}" rel="stylesheet" type="text/css" />

    <!-- Responsive datatable examples -->
    <link href="{% static 'libs/datatables.net-responsive-bs4/css/responsive.bootstrap4.min.css' %}" rel="stylesheet" type="text/css" />  
    <link href="{% static 'libs/bootstrap-datepicker/dist/css/bootstrap-datepicker.min.css' %}" rel="stylesheet" type="text/css">
    {% comment %} <link href="{% static 'libs/select2/css/select2.min.css' %}" rel="stylesheet" type="text/css" /> {% endcomment %}
    <link href="{% static 'css/bootstrap.min.css' %}" id="bootstrap-style" rel="stylesheet" type="text/css" />
    <!-- Icons Css -->
    <link href="{% static 'css/icons.min.css' %}" rel="stylesheet" type="text/css" />
    <!-- App Css-->
    <link href="{% static 'css/app.min.css' %}" id="app-style" rel="stylesheet" type="text/css" />

{% endblock %}
{% block contents %}
<div class="row">
    <div class="col-lg-4 col-md-6 col-sm-12">
        <!-- GHC {{ asset.costbf|floatformat:2|intcomma }} -->
        {% #stats-card  name = "totalusers" %}
            {% #stats-card-text name="totaltext" %}
                <p class="text-muted mb-2">Depreciation Year</p>
                <h5 class="mb-0">
                    
                    {% if depreciation %}
                        {{depreciation.accountingyear.period}}
                    {% else %}
                        No Current Year
                    {% endif %}
                        
                    <!-- GHC 0|floatformat:2|intcomm -->
                </h5>
            {% /stats-card-text %}
            {% #stats-card-avatar  name="totalav"%}
                    <i class="bx bxs-book-bookmark"></i> 
            {% /stats-card-avatar %}
        {% /stats-card %}
    </div>
    <div class="col-lg-4 col-md-6 col-sm-12">
        {% #stats-card name = "totalactive" %}
            {% #stats-card-text name="activetest" %}
                <p class="text-muted mb-2">Depreciation Value</p>
                <h5 class="mb-0">
                    {% if depreciation %}
                        GHC {{depreciation.depreciationvalue|floatformat:2|intcomma}}
                    {% else %}
                        GHC 0.00
                    {% endif %}
                    
                </h5>
            {% /stats-card-text %}
            {% #stats-card-avatar name="activeav" %}
                    <i class="bx bxs-note"></i> 
            {% /stats-card-avatar %}
        {% /stats-card %}
    </div>
    <div class="col-lg-4 col-md-6 col-sm-12">
        {% #stats-card  name = "totalinactive" %}
            {% #stats-card-text name="inactivetest" %}
                <p class="text-muted mb-2">Depreciation Status</p>
                <h5 class="mb-0">
                    
                    {% if depreciation %}
                     {{depreciation.status}}
                    {% else %}
                      
                        
                    {% endif %}
                  
                </h5>
            {% /stats-card-text %}
            {% #stats-card-avatar  name="inactiveav"%}
                    <i class="bx bxs-message-square-dots"></i> 
            {% /stats-card-avatar %}
        {% /stats-card %}
    </div>
</div>
<div class="row">
    <div class="col-lg-12">
        {% #card title="Current Asset Depreciation List" %}
        
        <div class="table-responsive">
            
            {% #table %}
                {% #thead %}
                    {% #tr name ="headrow" %}
                        {% #th name ="headid" %}ID{% /th %}
                        
                        {% #th name ="headName" %}Asset{% /th %}
                        {% #th name ="headName" %}Depreciation Value{% /th %}
                        
                    {% /tr %}
                {% /thead%}
                {% #tbody %}
                    {% for data in depreciation_detail  %}
                        {% #tr name ="bodyrow" %}
                            {% #td name ="groupid" %}{{data.id}}{% /td %}
                            {% #td name ="groupname" %}{{data.asset.asset_id }} --- {{ data.asset.description}}{% /td %}
                            {% #td name ="groupname" %}GHC {{data.depreciationvalue|floatformat:2|intcomma}}{% /td %}
                        {% /tr %}
                    {% endfor %}
                {% /tbody %}
            {% /table %}
           
            <!-- end table -->
        </div>
        <div class="row">
            <div class="col-6">
                <a href="{% url 'fixedassets:depreciation-list' %}" class="btn btn-primary mt-4 ">Close</a>
            </div>
        
        </div>
        {% /card %}
        <!--end card-->
       
</div>


{% endblock %}

<!-- {% block extra_content %}  
    {% #comfirmation   %}
        {% #avatar %}
            <i class="mdi mdi-trash-can-outline"></i>     
        {% /avatar %} 
        {% #comfirmationtext %}
            Are you sure you want to permanently delete this Assets.
        {% /comfirmationtext %} 

        {% #comfirmation_footer %}
            <a href="#" id ="deleteModalAnchor" class="btn btn-danger">Delete Now</a>
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        {% /comfirmation_footer %}     
    {% /comfirmation %}
 


{% endblock %} -->

{% block extra_javascript %}

     <!-- Required datatable js -->
     <script src="{% static 'libs/datatables.net/js/jquery.dataTables.min.js' %}"></script>
     <script src="{% static 'libs/datatables.net-bs4/js/dataTables.bootstrap4.min.js' %}"></script>
     <script src="{% static 'libs/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js' %}"></script>
     <!-- Buttons examples -->
     <script src="{% static 'libs/datatables.net-buttons/js/dataTables.buttons.min.js' %}"></script>
     <script src="{% static 'libs/datatables.net-buttons-bs4/js/buttons.bootstrap4.min.js' %}"></script>
     <script src="{% static 'libs/jszip/dist/jszip.min.js' %}"></script>
     <script src="{% static 'libs/pdfmake/build/pdfmake.min.js' %}"></script>
     <script src="{% static 'libs/pdfmake/build/vfs_fonts.js' %}"></script>
     <script src="{% static 'libs/datatables.net-buttons/js/buttons.html5.min.js' %}"></script>
     <script src="{% static 'libs/datatables.net-buttons/js/buttons.print.min.js' %}"></script>
     <script src="{% static 'libs/datatables.net-buttons/js/buttons.colVis.min.js' %}"></script>
     
     <!-- Responsive examples -->
     <script src="{% static 'libs/datatables.net-responsive/js/dataTables.responsive.min.js' %}"></script>
     <script src="{% static 'libs/datatables.net-responsive-bs4/js/responsive.bootstrap4.min.js' %}"></script>

     <!-- Datatable init js -->
     <script src="{% static 'js/pages/datatables.init.js' %}"></script>
     
    {% comment %} <script src="{% static 'js/auto_modal.js' %}"></script> {% endcomment %}

     <!-- <script>
        document.addEventListener("DOMContentLoaded", function() {
            var deleteAnchors = document.getElementsByClassName("delete-record");
            var deleteModalAnchor = document.getElementById("deleteModalAnchor");
            Array.from(deleteAnchors).forEach(function(anchor) {
              anchor.addEventListener("click", function(event) {
                event.preventDefault();
                var recordId = this.getAttribute("data-record-id"); 
                deleteModalAnchor.setAttribute("data-record-id", recordId);
                deleteModalAnchor.setAttribute("href", "/fixedassets/assets/" + recordId + "/delete/");
                deleteModalAnchor.style.display = "block";
              });
            });
          });
     </script> -->

{% endblock %}