django_project/dms/urls.py
from django.urls import path
from django.views.generic import TemplateView
from . import documents



app_name = 'dms'

urlpatterns = [
    #folder start
    path('filemanager/',documents.filemanager,name='filemanager-list'),
    path('filemanager/create-folder/',documents.add_folder,name='create-folder'),
    path('filemanager/folder/<str:folder_id>/pin_folder',documents.pin_folder,name='pin-folder'),
    path('filemanager/folder/<str:folder_id>/unpin_folder',documents.unpin_folder,name='unpin-folder'),
    path('filemanager/folder/<str:folder_id>/update/',documents.edit_folder,name='edit-folder'),
    path('filemanager/files/new/',documents.add_file,name='new-file'),
    path('filemanager/files/<str:file_id>/update/',documents.edit_file,name='edit-file'),
    
    path('filemanager/folder/<str:folder_id>/detail',documents.files,name='folder-detail'),
    path('filemanager/folder/file/<str:file_id>/generate/',documents.add_document_detail,name='add-document_detail'),
    path('filemanager/folder/file/<str:file_id>/edit/',documents.edit_document_detail,name='edit-document_detail'),
    path('filemanager/folder/document/paragraph/<str:item_id>/item/remove/',documents.remove_document_item,name='remove-document_item'),
    path('filemanager/folder/document/<str:document_id>/draft/',documents.save_as_draft,name='save-as_draft'),
    path('filemanager/folder/document/<str:document_id>/approve/',documents.sendpprove_document,name='sendpprove-document'),
    path('filemanager/files/<str:file_id>/currency/',documents.add_document_currency,name='add-document_currency'),
    path('filemanager/files/<str:file_id>/currency/edit/',documents.edit_document_currency,name='edit-document_currency'),
    path('filemanager/folder/<str:file_id>/dudget/',documents.add_document_budget,name='add-document_budget'),
    path('filemanager/folder/document/dudget/<str:item_id>/item/remove/',documents.remove_budget_item,name='remove-budget_item'),
    # path('filemanager/folder/file/<str:file_id>/generate/',documents.add_document_detail,name='add-document_detail')
    path('filemanager/folder/document/document/<str:document_id>/attachement/',documents.add_attachment,name='add-attachment'),
    path('filemanager/folder/document/document/<str:item_id>/attachement/remove/',documents.remove_attachemnt,name='remove-attachemnt'),
    path('filemanager/folder/document/document/<str:document_id>/attachement/detail/',documents.view_attachment,name='view-attachment'),
    path('filemanager/folder/document/document/<str:document_id>/minute/',documents.add_munites,name='add-munites'),

    path('filemanager/folder/document/<str:document_id>/save/',documents.save_to_send,name='save-to-send'),
    path('filemanager/folder/document/<str:file_id>/detail/',documents.view_document_detail,name='view-document_detail'),
    path('filemanager/folder/document/<str:document_id>/return_or_cancel/',documents.return_document,name='return-document'),
    path('filemanager/folder/document/<str:file_id>/approved_amount/',documents.add_approved_amount,name='add-approved_amount'),
    path('filemanager/file/<str:file_id>/beneficiary/', documents.document_beneficiary_upload,name='document-beneficiary-upload'),
    path('filemanager/file/<str:file_id>/pull_low_stock/',documents.pull_low_stock_product,name='pull-product'),
    


    
    #Folder end
    
]

django_project/erpproject/urls.py
from django.contrib import admin
from django.urls import path,include
from erpproject import views

from django.contrib.auth.decorators import login_required
from django.views.generic import TemplateView

from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import handler404


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.DashboardView,name='dashboard'), 
    path('authentication/', include('authentication.urls', namespace='authentication')), 
    path('inventory/', include('inventory.urls', namespace='inventory')), 
    path('company/', include('company.urls', namespace='company')), 
    path('accounting/',include('accounting.urls', namespace='accounting')),
    path('dms/',include('dms.urls',namespace='dms')),
    path('supplychain/',include('supply_chain.urls',namespace='supplychain')),
    path('purchaseorder/',include('purchase_order.urls',namespace='purchaseorder')),
    path('fixedassets/',include('fixedassets.urls',namespace='fixedassets')),
    path('helpdesk/',include('helpdesk.urls',namespace='helpdesk')),
]

handler404 = 'authentication.auth.error_404_view'
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django_project/inventory/urls.py
from django.urls import path
from .import category,dashboard,brand,measurement,products,supplier,restock,job,requisition,reports,utils,allocation,closingstock

app_name = 'inventory'

urlpatterns = [
    path('dashboard/',dashboard.InventoryDashboardView,name='dashboard'), 

    #category start
    path('categories/',category.category,name='category-list'),
    path('categories/add/',category.add_category,name='new-category'),
    path('categories/<str:category_id>/update/',category.edit_category,name='edit-category'),
    path('categories/<str:category_id>/delete/',category.delete_category,name='delete-category'),
    path('categories/upload/',category.category_upload,name='upload-category'),
    #categoryend

    #Brand Start
    path('brand/',brand.brand,name='brand-list'),
    path('brnad/add/',brand.add_brand,name='new-brand'),
    path('brand/<str:brand_id>/update/',brand.edit_brand,name='edit-brand'),
    path('brand/<str:brand_id>/delete/',brand.delete_brand,name='delete-brand'),
    path('brand/upload/',brand.brand_upload,name='upload-brand'),
    #Brand End

    #measure Start
    path('measurement/',measurement.measurement,name='measurement-list'),
    path('measurement/add/',measurement.add_measurement,name='new-measurement'),
    path('measurement/<str:measurement_id>/update/',measurement.edit_measurement,name='edit-measurement'),
    path('measurement/<str:measurement_id>/delete/',measurement.delete_measurement,name='delete-measurement'),
    path('measurement/upload/',measurement.measurement_upload,name='upload-measurement'),
    #Brand End

    #product Start
    path('product/',products.product,name='product-list'),
    path('product/add/',products.add_product,name='new-product'),
    path('product/<str:product_id>/update/',products.edit_product,name='edit-product'),
    path('product/<str:product_id>/delete/',products.delete_product,name='delete-product'),
    path('product/upload/',products.product_upload,name='upload-product'),
    path('product/<str:product_id>/view/',products.detail_product,name='view-product'),
    path('assets/avialable/',products.aviable_assets,name='aviable-assets'),
    path('products/closing_stock/',closingstock.closing_stock,name='closing-stock'),
    path('products/closing_stock/<str:closing_stock_id>/',closingstock.closingstock_product,name='closing-stock-products'),
    path('products/closing_stock/<str:closing_stock_product_id>/detail/',closingstock.closingstock_detail_product,name='closing-stock-products-detail'),
    path('product/close/stock/',closingstock.close_stock,name='close-stock'),
    #Product End

    #supplier Start
    path('supplier/',supplier.supplier,name='supplier-list'),
    path('supplier/add/',supplier.add_supplier,name='new-supplier'),
    path('supplier/<str:supplier_id>/products/',supplier.add_supplier_detail,name='supplier-products'),
    path('supplier/<str:supplier_id>/prodduct/remove/',supplier.delete_supplier_item,name='remove-product'),
    path('supplier/<str:supplier_id>/update/',supplier.edit_supplier,name='edit-supplier'),
    path('supplier/<str:supplier_id>/delete/',supplier.delete_supplier,name='delete-supplier'),
    path('supplier/upload/',supplier.supplier_upload,name='upload-supplier'),
    #supplier End

    #restock Start
    path('restock/',restock.restock,name='restock-list'),
    path('restock/add/',restock.add_restock,name='new-restock'),
    path('restock/<str:restock_id>/details/add/',restock.add_restock_detail,name='add-restock-details'),
    path('restock/<str:restock_id>/details/update/',restock.edit_restock_detail,name='edit-restock-details'),
    path('restock/<str:restock_id>/details/upload/',restock.restock_detail_upload,name='upload-restock-details-items'),
    path('restock/<str:restock_id>/details/delete/',restock.delete_restock_item,name='delete-restock-details-item'),
    path('restock/<str:restock_id>/update/',restock.edit_restock,name='edit-restock'),
    path('restock/<str:restock_id>/delete/',restock.delete_restock,name='delete-restock'),
    path('restock/<str:restock_id>/approve/',restock.approve_restock,name='approve-restock'),
    path('restock/<str:restock_id>/cancel/',restock.cancel_restock,name='cancel-restock'),
    path('restock/<str:restock_id>/reverse/',restock.reverse_restock,name='reverse-restock'),
   
    #restock End

    #certification Start
    path('job/',job.job_cert,name='job-list'),
    path('job/add/',job.add_job,name='new-job'),
    path('job/<str:job_id>/details/add/',job.add_job_detail,name='add-job-details'),
    path('job/<str:job_id>/details/update/',job.edit_job_detail,name='edit-job-details'),
    path('job/<str:job_id>/details/upload/',job.job_detail_upload,name='upload-job-details-items'),
    path('job/<str:job_id>/details/delete/',job.delete_job_item,name='delete-job-details-item'),
    path('job/<str:job_id>/update/',job.edit_job,name='edit-job'),
    path('job/<str:job_id>/delete/',job.delete_job,name='delete-job'),
    path('job/<str:job_id>/approve/',job.approve_job,name='approve-job'),
    path('job/<str:job_id>/cancel/',job.cancel_job,name='cancel-job'),
    path('job/<str:job_id>/reverse/',job.reverse_job,name='reverse-job'),
    path('job/loadproduct/',job.load_product,name='load-product'),
    #certification End

    # Requisition Start
    path('requisition/personnal/',requisition.personnalrequisition,name='personnal-requisition-list'),
    path('requisition/pending/',requisition.pendingrequisition,name='pending-requisition-list'),
    path('requisition/awaiting/capital/',requisition.awaitingcapitalrequisition,name='awaiting-capital-requisition-list'),
    path('requisition/awaiting/consumable/',requisition.awaitingconsumablerequisition,name='awaiting-consumable-requisition-list'),
    path('requisition/approved/',requisition.requisitionissue,name='approved-requisition-list'),

    path('requisition/add/',requisition.add_requisition,name='new-requisition'),
    path('requisition/<str:requisition_id>/details/add/',requisition.add_requisition_detail,name='add-requisition-details'),
    path('requisition/<str:requisition_id>/details/update/',requisition.edit_requisition_detail,name='edit-requisition-details'),
    path('requisition/<str:requisition_id>/details/delete/',requisition.delete_requisition_item,name='delete-requisition-details-item'),
    path('requisition/<str:requisition_id>/update/',requisition.edit_requisition,name='edit-requisition'),
    path('requisition/<str:requisition_id>/delete/',requisition.delete_reqisition,name='delete-requisition'),
    path('requisition/<str:requisition_id>/approve/',requisition.approve_requisition,name='approve-requisition'),
    path('requisition/<str:requisition_id>/approve/item/',requisition.approve_individual_items,name='approve-requisition-items'),
    path('requisition/<str:requisition_id>/cancel/item/',requisition.reject_individual_items,name='cancel-requisition-items'),
    path('requisition/<str:requisition_id>/approve/quantity/',requisition.approve_quantity,name='approve-requisition-quantity'),
    path('requisition/<str:requisition_id>/<str:detailbatch_id>/approve/quantity/',requisition.store_approve_quantity,name='store-approve-quantity'),
    path('requisition/<str:requisition_id>/cancel/',requisition.cancel_requisition,name='cancel-requisition'),
    path('requisition/<str:requisition_id>/reverse/',requisition.reverse_requisition,name='reverse-requisition'),
    path('requisition/<str:requisition_id>/send/',requisition.send_notification_reqisition,name='send-requisition'),
    path('requisition/<str:requisition_id>/list-inventory/',requisition.list_inventory,name='list-inventory'),
    path('requisition/<str:requisition_id>/issue/<str:asset_id>/item/',requisition.store_assets_issue,name='store-assets-issue'),
    
    # Requisition End

    #report Start
    path('reports/requisition/',reports.reportrequisition,name='report-requisition'),
    path('reports/requisition/devisional/statistics/',reports.regionrequisition,name='devisional-statistics'),
    path('reports/requisition/sub_devisional/statistics/',reports.districtrequisition,name='sub-devisional-statistics'),
    path('reports/product/low-stock/statistics/',reports.low_stock_alert,name='low-stock-alert'),
    path('reports/products/expired/',reports.expire_products,name='expire-products'),
    path('reports/products/<str:product_id>/forcast/',reports.forecast_view,name='product-forcast'),
    path('low-stock/',reports.check_product_stock,name='low-stock'),
    path('assets/assigned-assets/',reports.assigned_assets,name='assigned-assets'),
    path('assets/return/<str:assets_id>/asset/',reports.return_assets,name='return-assets'),
    #report End

    #allocation Start
    path('allocation/',allocation.allocation,name='allocation-list'),
    path('allocation/add/',allocation.add_allocation,name='new-allocation'),
    path('allocation/<str:allocation_id>/destination/',allocation.add_allocation_destination,name='add-allocation-destination'),
    path('allocation/<str:allocation_id>/destination/update/',allocation.edit_allocation_destination,name='edit-allocation-destination'),
    path('allocation/<str:allocation_id>/destination/item/delete/',allocation.delete_allocation_destination,name='delete-allocation-destination'),
    path('allocation/<str:allocation_id>/destination/release/',allocation.release_allocation_destination,name='release-allocation-destination'),
    path('allocation/<str:destination_id>/destination/product/add/',allocation.add_allocation_detail,name='add-destination-item'),
    path('allocation/<str:destination_id>/destination/product/upload/',allocation.allocation_detail_upload,name='allocation-detail-upload'),
    path('allocation/<str:destination_id>/destination/product/delete/',allocation.delete_destination_item,name='delete-destination-item'),
    path('allocation/<str:allocation_id>/destination/detail/',allocation.view_allocation_destination,name='view-allocation-destination'),

django_project/purchase_order/urls.py
from django.urls import path
from .import purchase_order

app_name = 'purchaseorder'

urlpatterns = [
    path('purchase_requisition/',purchase_order.purchase_requisition,name='purchase-requisition-list'),
    path('purchase_requisition/create/<str:document_product_id>/',purchase_order.create_purchase_order,name='new-purchase-requisition'),
    path('add_purchase_requisition/<str:purchase_requisition_id>/update/',purchase_order.add_purchase_requisition,name='update-purchase-requisition'),
    path('purchase_requisition/<str:purchase_requisition_id>/Detail/',purchase_order.view_purchase_requisition,name='purchase-requisition-detail'),
    path('approve_purchase_requisition/<str:purchase_requisition_id>/approve/',purchase_order.approve_purchase_requisition,name='approve-purchase-requisition'),
    path('cancel_purchase_requisition/<str:purchase_requisition_id>/cancel/',purchase_order.cancel_purchase_requisition,name='cancel-purchase-requisition'),
    path('complete_supplier_selection/<str:purchase_requisition_id>/confirm/',purchase_order.complete_supplier_selection,name='complete-supplier-selection'),
    path('add_quotation_requisition/<str:quotation_id>/quotation/',purchase_order.add_quotation_requisition,name='quotation-form'),
    path('approve_quotation_requisition/<str:quotation_id>/approve/',purchase_order.approve_quotation_requisition,name='approve-quotation'),
    path('reject_quotation_requisition/<str:quotation_id>/reject/',purchase_order.reject_quotation_requisition,name='reject-quotation'),

    path('lpo/<str:purchase_requisition_id>/new/',purchase_order.create_lpo,name='new-lpo'),
    path('lpo/<str:lpo_id>/detail/',purchase_order.view_lpo,name='detail-lpo'),
    path('lpo/<str:lpo_id>/approve/',purchase_order.approve_lpo,name='approve-lpo'),
    path('lpo/<str:lpo_id>/cancel/',purchase_order.cancel_lpo,name='cancel-lpo'),
    path('lpo/',purchase_order.lpo,name='lpo'),


]

django_project/purchase_order/forms.py
from django import forms
from .models import *
from django.forms.widgets import NumberInput


class PurchaseRquisitionForm(forms.ModelForm):
       
    quantity = forms.IntegerField(label=False)
    unit_price=forms.FloatField(label=False) 
    class Meta:
        model = PurchaseRequisition
        fields = ('purchase_requisition_date','quantity','unit_price')


class DecisionRquisitionForm(forms.ModelForm):
       
    reason = forms.CharField(
    widget=forms.Textarea(attrs={'maxlength': 1200}),
        label=False,required=True)
    class Meta:
        model = PurchaseRequisition_Suppliers
        fields = ('reason',)

class QoutationForm(forms.ModelForm):
    amount=forms.FloatField(label=False) 
    class Meta:
        model = PurchaseRequisition_Suppliers
        fields = ('amount',)

django_project/purchase_order/views.py
from django.shortcuts import render

# Create your views here.

django_project/templates/partials/purchaseorder/purchasebase.html
{% load static %}
<!DOCTYPE html>
<html lang="en" >

    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta content="Premium Multipurpose Admin & Dashboard Template" name="description" />
        <meta content="Themesbrand" name="author" />
    
        <title>{{heading}} ERP SYSTEM </title>
        
        <!-- App favicon -->
        <link rel="shortcut icon" href="{% static 'images/favicon.ico' %}">
        {% block css %}
        {% block extra_css %}
        {% endblock %}
        <!-- Bootstrap Css -->
        <link href="{% static 'css/bootstrap.min.css' %}" id="bootstrap-style" rel="stylesheet" type="text/css" />
        <!-- Icons Css -->
        <link href="{% static 'css/icons.min.css' %}" rel="stylesheet" type="text/css" />
        <!-- App Css-->
        <link href="{% static 'css/app.min.css' %}" id="app-style" rel="stylesheet" type="text/css" />
        {% endblock css %}
    </head>
    


<body data-sidebar="dark" data-bs-theme="dark" >
    <!-- Loader -->
    <div id="preloader">
        <div id="status">
            <div class="spinner-chase">
                <div class="chase-dot"></div>
                <div class="chase-dot"></div>
                <div class="chase-dot"></div>
                <div class="chase-dot"></div>
                <div class="chase-dot"></div>
                <div class="chase-dot"></div>
            </div>
        </div>
    </div> 
    <!-- Begin page -->
    <div id="layout-wrapper">
        {% block header %}
        {% include 'partials/header.html' %}
        {% endblock %}
        {% block sidebar %}
        {% include 'partials/purchaseorder/purchasesidebar.html' %}
        {% endblock %}
  
        <!-- ============================================================== -->
        <!-- Start right Content here -->
        <!-- ============================================================== -->
        <div class="main-content">
            <div class="page-content">
                <div class="container-fluid">
                    <!-- start page title -->
                    <div class="row">   
                        <div class="col-12">
                            <div class="page-title-box d-sm-flex align-items-center justify-content-between">
                                <h4 class="mb-sm-0 font-size-18">{{heading}}</h4>
                                
                                <div class="page-title-right">
                                    <ol class="breadcrumb m-0">
                                        <li class="breadcrumb-item"><a href="javascript: void(0);">{{pageview}}</a></li>
                                        <li class="breadcrumb-item active">{{heading}}</li>
                                    </ol>
                                </div>

                            </div>
                        </div>
                    </div>
                    <!-- end page title -->
                    
                    {% if messages %}
                    {% for message in messages %}
                    <div class="page-title-box d-flex align-items-center justify-content-center">
                        <div class="alert {{ message.tags }} alert-dismissible fade show" role="alert">
                            <i class="mdi mdi-check-all me-2"></i>
                                {{ message | safe }}
                            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                      </div>
                    </div>
                    {% endfor %}
                {% endif %}
                    {% block contents %}

                    {% endblock %}
                </div>
                <!-- container-fluid -->
            </div>
            <!-- End Page-content -->
        

            {% block extra_content %}            
            {% endblock %}
                
            {% block footer %}
            {% include 'partials/footer.html' %}
            {% endblock %}
        </div>
        <!-- end main content-->
    </div>
    <!-- END layout-wrapper -->
    {% block Subscribe %}
    {% endblock %} 

    {% block r_sidebar %}
    {% include 'partials/rightsidebar.html' %}
    {% endblock %}
    {% block javascript %}
    <!-- JAVASCRIPT -->
    <script src="{% static 'libs/jquery/dist/jquery.min.js' %}"></script>
    <script src="{% static 'libs/bootstrap/dist/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'libs/metismenu/dist/metisMenu.min.js' %}"></script>
    <script src="{% static 'libs/simplebar/dist/simplebar.min.js' %}"></script>
    <script src="{% static 'libs/node-waves/dist/waves.min.js' %}"></script>
    <script src="{% static 'js/htmx.min.js' %}" defer></script>
    <script src="{% static 'js/bootstrap-toastr.init.js' %}"></script>
    <script src="{% static 'js/auto_modal.js' %}"></script>
    <script src="{% static 'js/comfirmationmodal.js' %}"></script>
    <script src="{% static 'js/app.js' %}"></script>  
    <script src="{% static 'js/jquery.js' %}"></script> 
    
    {% comment %} <script src="{% static 'js/auto_modal.js' %}"></script>   {% endcomment %}

        {% block extra_javascript %}
            <script src="{% static 'js/pages/bootstrap-toastr.init.js' %}"></script>
            <script src="{% static 'js/pages/alerts.init.js' %}"></script>
            <script src="{% static 'js/comfirmationmodal.js' %}"></script>
            <script src="{% static 'js/jquery.js' %}"></script> 
            <script>
                $("#id_devision").change(function () {
                    var DevisionId = $(this).val()
                    console.log(DevisionId)
                var url = '/authentication/user/load_district/';  // get the url of the `load_cities` view
                var DevisionId = $(this).val();  // get the selected country ID from the HTML input
                
                $.ajax({                       // initialize an AJAX request
                    url: url,                    // set the url of the request (= localhost:8000/hr/ajax/load-cities/)
                    data: {
                    'devision': DevisionId      // add the country id to the GET parameters
                    },
                    success: function (data) {   // `data` is the return of the `load_cities` view function
                    $("#id_sub_division").html(data);  // replace the contents of the city input with the data that came from the server
                    }
                });
            
                });
            </script>
         {% endblock %}
    
    {% endblock javascript %}
        </body>

    </html>
    

django_project/templates/partials/purchaseorder/purchasesidebar.html
{% load static %} {% block sidebar %}
  <!-- ========== Left Sidebar Start ========== -->
  <div class="vertical-menu">
    <div data-simplebar class="h-100">
      <!-- - Sidemenu -->
      <div id="sidebar-menu">
        <!-- Left Menu Start -->
        <ul class="metismenu list-unstyled" id="side-menu">
          <li class="menu-title" key="t-menu">Menu</li>
          
            <li>
                <a href="javascript: void(0);" class="has-arrow waves-effect">
                <i class="bx bx-data"></i>
                <span key="t-products">Purchase Order</span>
                </a>
                <ul class="sub-menu" aria-expanded="false">
                    {% if perms.inventory.custom_view_supplier %}
                        <li>
                            <a href="{% url 'inventory:supplier-list' %}" key="t-supplier">Suppliers</a>
                        </li> 
                    {% endif %}
                    {% if perms.purchase_order.custom_view_purchase_requisition %}
                        <li>
                            <a href="{% url 'purchaseorder:purchase-requisition-list' %}" key="t-supplier">Purchase Requisiton</a>
                        </li> 
                    {% endif %}
                    {% if perms.purchase_order.custom_view_lpo %}
                        <li>
                            <a href="{% url 'purchaseorder:lpo' %}" key="t-supplier">LPO</a>
                        </li> 
                    {% endif %}
                </ul>
            </li>
            {% if perms.inventory.custom_view_job_certification %}
            <li>
                <a href="javascript: void(0);" class="has-arrow waves-effect">
                <i class="bx bx-data"></i>
                <span key="t-products">Certififaction</span>
                </a>
                <ul class="sub-menu" aria-expanded="false">
                    
                {% if perms.inventory.custom_view_restock %}
                    <li>
                        <a href="{% url 'inventory:restock-list' %}" key="t-product">Consumable</a>
                    </li> 
                {% endif %}
                {% if perms.inventory.custom_view_job_certification %}
                    <li>
                        <a href="{% url 'inventory:job-list' %}" key="t-product">Capital</a>
                    </li> 
                {% endif %}
                
                </ul>
            </li>
          {% endif %}
        
          
          
        </ul>
      </div>
      <!-- Sidebar -->
    </div>
  </div>
  <!-- Left Sidebar End -->
{% endblock %}