django_project/dms/urls.py
from django.urls import path
from django.views.generic import TemplateView
from . import documents



app_name = 'dms'

urlpatterns = [
    #folder start
    path('filemanager/',documents.filemanager,name='filemanager-list'),
    path('filemanager/create-folder/',documents.add_folder,name='create-folder'),
    path('filemanager/folder/<str:folder_id>/pin_folder',documents.pin_folder,name='pin-folder'),
    path('filemanager/folder/<str:folder_id>/unpin_folder',documents.unpin_folder,name='unpin-folder'),
    path('filemanager/folder/<str:folder_id>/update/',documents.edit_folder,name='edit-folder'),
    path('filemanager/files/new/',documents.add_file,name='new-file'),
    path('filemanager/files/<str:file_id>/update/',documents.edit_file,name='edit-file'),
    
    path('filemanager/folder/<str:folder_id>/detail',documents.files,name='folder-detail'),
    path('filemanager/folder/file/<str:file_id>/generate/',documents.add_document_detail,name='add-document_detail'),
    path('filemanager/folder/file/<str:file_id>/edit/',documents.edit_document_detail,name='edit-document_detail'),
    path('filemanager/folder/document/paragraph/<str:item_id>/item/remove/',documents.remove_document_item,name='remove-document_item'),
    path('filemanager/folder/document/<str:document_id>/draft/',documents.save_as_draft,name='save-as_draft'),
    path('filemanager/folder/document/<str:document_id>/approve/',documents.sendpprove_document,name='sendpprove-document'),
    path('filemanager/files/<str:file_id>/currency/',documents.add_document_currency,name='add-document_currency'),
    path('filemanager/files/<str:file_id>/currency/edit/',documents.edit_document_currency,name='edit-document_currency'),
    path('filemanager/folder/<str:file_id>/dudget/',documents.add_document_budget,name='add-document_budget'),
    path('filemanager/folder/document/dudget/<str:item_id>/item/remove/',documents.remove_budget_item,name='remove-budget_item'),
    # path('filemanager/folder/file/<str:file_id>/generate/',documents.add_document_detail,name='add-document_detail')
    path('filemanager/folder/document/document/<str:document_id>/attachement/',documents.add_attachment,name='add-attachment'),
    path('filemanager/folder/document/document/<str:item_id>/attachement/remove/',documents.remove_attachemnt,name='remove-attachemnt'),
    path('filemanager/folder/document/document/<str:document_id>/attachement/detail/',documents.view_attachment,name='view-attachment'),
    path('filemanager/folder/document/document/<str:document_id>/minute/',documents.add_munites,name='add-munites'),

    path('filemanager/folder/document/<str:document_id>/save/',documents.save_to_send,name='save-to-send'),
    path('filemanager/folder/document/<str:file_id>/detail/',documents.view_document_detail,name='view-document_detail'),
    path('filemanager/folder/document/<str:document_id>/return_or_cancel/',documents.return_document,name='return-document'),
    path('filemanager/folder/document/<str:file_id>/approved_amount/',documents.add_approved_amount,name='add-approved_amount'),
    path('filemanager/file/<str:file_id>/beneficiary/', documents.document_beneficiary_upload,name='document-beneficiary-upload'),
    path('filemanager/file/<str:file_id>/pull_low_stock/',documents.pull_low_stock_product,name='pull-product'),
    


    
    #Folder end
    
]

django_project/erpproject/urls.py
from django.contrib import admin
from django.urls import path,include
from erpproject import views

from django.contrib.auth.decorators import login_required
from django.views.generic import TemplateView

from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import handler404


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.DashboardView,name='dashboard'), 
    path('authentication/', include('authentication.urls', namespace='authentication')), 
    path('inventory/', include('inventory.urls', namespace='inventory')), 
    path('company/', include('company.urls', namespace='company')), 
    path('accounting/',include('accounting.urls', namespace='accounting')),
    path('dms/',include('dms.urls',namespace='dms')),
    path('supplychain/',include('supply_chain.urls',namespace='supplychain')),
    path('purchaseorder/',include('purchase_order.urls',namespace='purchaseorder')),
    path('fixedassets/',include('fixedassets.urls',namespace='fixedassets')),
    path('helpdesk/',include('helpdesk.urls',namespace='helpdesk')),
]

handler404 = 'authentication.auth.error_404_view'
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django_project/inventory/urls.py
from django.urls import path
from .import category,dashboard,brand,measurement,products,supplier,restock,job,requisition,reports,utils,allocation,closingstock

app_name = 'inventory'

urlpatterns = [
    path('dashboard/',dashboard.InventoryDashboardView,name='dashboard'), 

    #category start
    path('categories/',category.category,name='category-list'),
    path('categories/add/',category.add_category,name='new-category'),
    path('categories/<str:category_id>/update/',category.edit_category,name='edit-category'),
    path('categories/<str:category_id>/delete/',category.delete_category,name='delete-category'),
    path('categories/upload/',category.category_upload,name='upload-category'),
    #categoryend

    #Brand Start
    path('brand/',brand.brand,name='brand-list'),
    path('brnad/add/',brand.add_brand,name='new-brand'),
    path('brand/<str:brand_id>/update/',brand.edit_brand,name='edit-brand'),
    path('brand/<str:brand_id>/delete/',brand.delete_brand,name='delete-brand'),
    path('brand/upload/',brand.brand_upload,name='upload-brand'),
    #Brand End

    #measure Start
    path('measurement/',measurement.measurement,name='measurement-list'),
    path('measurement/add/',measurement.add_measurement,name='new-measurement'),
    path('measurement/<str:measurement_id>/update/',measurement.edit_measurement,name='edit-measurement'),
    path('measurement/<str:measurement_id>/delete/',measurement.delete_measurement,name='delete-measurement'),
    path('measurement/upload/',measurement.measurement_upload,name='upload-measurement'),
    #Brand End

    #product Start
    path('product/',products.product,name='product-list'),
    path('product/add/',products.add_product,name='new-product'),
    path('product/<str:product_id>/update/',products.edit_product,name='edit-product'),
    path('product/<str:product_id>/delete/',products.delete_product,name='delete-product'),
    path('product/upload/',products.product_upload,name='upload-product'),
    path('product/<str:product_id>/view/',products.detail_product,name='view-product'),
    path('assets/avialable/',products.aviable_assets,name='aviable-assets'),
    path('products/closing_stock/',closingstock.closing_stock,name='closing-stock'),
    path('products/closing_stock/<str:closing_stock_id>/',closingstock.closingstock_product,name='closing-stock-products'),
    path('products/closing_stock/<str:closing_stock_product_id>/detail/',closingstock.closingstock_detail_product,name='closing-stock-products-detail'),
    path('product/close/stock/',closingstock.close_stock,name='close-stock'),
    #Product End

    #supplier Start
    path('supplier/',supplier.supplier,name='supplier-list'),
    path('supplier/add/',supplier.add_supplier,name='new-supplier'),
    path('supplier/<str:supplier_id>/products/',supplier.add_supplier_detail,name='supplier-products'),
    path('supplier/<str:supplier_id>/prodduct/remove/',supplier.delete_supplier_item,name='remove-product'),
    path('supplier/<str:supplier_id>/update/',supplier.edit_supplier,name='edit-supplier'),
    path('supplier/<str:supplier_id>/delete/',supplier.delete_supplier,name='delete-supplier'),
    path('supplier/upload/',supplier.supplier_upload,name='upload-supplier'),
    #supplier End

    #restock Start
    path('restock/',restock.restock,name='restock-list'),
    path('restock/add/',restock.add_restock,name='new-restock'),
    path('restock/<str:restock_id>/details/add/',restock.add_restock_detail,name='add-restock-details'),
    path('restock/<str:restock_id>/details/update/',restock.edit_restock_detail,name='edit-restock-details'),
    path('restock/<str:restock_id>/details/upload/',restock.restock_detail_upload,name='upload-restock-details-items'),
    path('restock/<str:restock_id>/details/delete/',restock.delete_restock_item,name='delete-restock-details-item'),
    path('restock/<str:restock_id>/update/',restock.edit_restock,name='edit-restock'),
    path('restock/<str:restock_id>/delete/',restock.delete_restock,name='delete-restock'),
    path('restock/<str:restock_id>/approve/',restock.approve_restock,name='approve-restock'),
    path('restock/<str:restock_id>/cancel/',restock.cancel_restock,name='cancel-restock'),
    path('restock/<str:restock_id>/reverse/',restock.reverse_restock,name='reverse-restock'),
   
    #restock End

    #certification Start
    path('job/',job.job_cert,name='job-list'),
    path('job/add/',job.add_job,name='new-job'),
    path('job/<str:job_id>/details/add/',job.add_job_detail,name='add-job-details'),
    path('job/<str:job_id>/details/update/',job.edit_job_detail,name='edit-job-details'),
    path('job/<str:job_id>/details/upload/',job.job_detail_upload,name='upload-job-details-items'),
    path('job/<str:job_id>/details/delete/',job.delete_job_item,name='delete-job-details-item'),
    path('job/<str:job_id>/update/',job.edit_job,name='edit-job'),
    path('job/<str:job_id>/delete/',job.delete_job,name='delete-job'),
    path('job/<str:job_id>/approve/',job.approve_job,name='approve-job'),
    path('job/<str:job_id>/cancel/',job.cancel_job,name='cancel-job'),
    path('job/<str:job_id>/reverse/',job.reverse_job,name='reverse-job'),
    path('job/loadproduct/',job.load_product,name='load-product'),
    #certification End

    # Requisition Start
    path('requisition/personnal/',requisition.personnalrequisition,name='personnal-requisition-list'),
    path('requisition/pending/',requisition.pendingrequisition,name='pending-requisition-list'),
    path('requisition/awaiting/capital/',requisition.awaitingcapitalrequisition,name='awaiting-capital-requisition-list'),
    path('requisition/awaiting/consumable/',requisition.awaitingconsumablerequisition,name='awaiting-consumable-requisition-list'),
    path('requisition/approved/',requisition.requisitionissue,name='approved-requisition-list'),

    path('requisition/add/',requisition.add_requisition,name='new-requisition'),
    path('requisition/<str:requisition_id>/details/add/',requisition.add_requisition_detail,name='add-requisition-details'),
    path('requisition/<str:requisition_id>/details/update/',requisition.edit_requisition_detail,name='edit-requisition-details'),
    path('requisition/<str:requisition_id>/details/delete/',requisition.delete_requisition_item,name='delete-requisition-details-item'),
    path('requisition/<str:requisition_id>/update/',requisition.edit_requisition,name='edit-requisition'),
    path('requisition/<str:requisition_id>/delete/',requisition.delete_reqisition,name='delete-requisition'),
    path('requisition/<str:requisition_id>/approve/',requisition.approve_requisition,name='approve-requisition'),
    path('requisition/<str:requisition_id>/approve/item/',requisition.approve_individual_items,name='approve-requisition-items'),
    path('requisition/<str:requisition_id>/cancel/item/',requisition.reject_individual_items,name='cancel-requisition-items'),
    path('requisition/<str:requisition_id>/approve/quantity/',requisition.approve_quantity,name='approve-requisition-quantity'),
    path('requisition/<str:requisition_id>/<str:detailbatch_id>/approve/quantity/',requisition.store_approve_quantity,name='store-approve-quantity'),
    path('requisition/<str:requisition_id>/cancel/',requisition.cancel_requisition,name='cancel-requisition'),
    path('requisition/<str:requisition_id>/reverse/',requisition.reverse_requisition,name='reverse-requisition'),
    path('requisition/<str:requisition_id>/send/',requisition.send_notification_reqisition,name='send-requisition'),
    path('requisition/<str:requisition_id>/list-inventory/',requisition.list_inventory,name='list-inventory'),
    path('requisition/<str:requisition_id>/issue/<str:asset_id>/item/',requisition.store_assets_issue,name='store-assets-issue'),
    
    # Requisition End

    #report Start
    path('reports/requisition/',reports.reportrequisition,name='report-requisition'),
    path('reports/requisition/devisional/statistics/',reports.regionrequisition,name='devisional-statistics'),
    path('reports/requisition/sub_devisional/statistics/',reports.districtrequisition,name='sub-devisional-statistics'),
    path('reports/product/low-stock/statistics/',reports.low_stock_alert,name='low-stock-alert'),
    path('reports/products/expired/',reports.expire_products,name='expire-products'),
    path('reports/products/<str:product_id>/forcast/',reports.forecast_view,name='product-forcast'),
    path('low-stock/',reports.check_product_stock,name='low-stock'),
    path('assets/assigned-assets/',reports.assigned_assets,name='assigned-assets'),
    path('assets/return/<str:assets_id>/asset/',reports.return_assets,name='return-assets'),
    #report End

    #allocation Start
    path('allocation/',allocation.allocation,name='allocation-list'),
    path('allocation/add/',allocation.add_allocation,name='new-allocation'),
    path('allocation/<str:allocation_id>/destination/',allocation.add_allocation_destination,name='add-allocation-destination'),
    path('allocation/<str:allocation_id>/destination/update/',allocation.edit_allocation_destination,name='edit-allocation-destination'),
    path('allocation/<str:allocation_id>/destination/item/delete/',allocation.delete_allocation_destination,name='delete-allocation-destination'),
    path('allocation/<str:allocation_id>/destination/release/',allocation.release_allocation_destination,name='release-allocation-destination'),
    path('allocation/<str:destination_id>/destination/product/add/',allocation.add_allocation_detail,name='add-destination-item'),
    path('allocation/<str:destination_id>/destination/product/upload/',allocation.allocation_detail_upload,name='allocation-detail-upload'),
    path('allocation/<str:destination_id>/destination/product/delete/',allocation.delete_destination_item,name='delete-destination-item'),
    path('allocation/<str:allocation_id>/destination/detail/',allocation.view_allocation_destination,name='view-allocation-destination'),

django_project/purchase_order/urls.py
from django.urls import path
from .import purchase_order

app_name = 'purchaseorder'

urlpatterns = [
    path('purchase_requisition/',purchase_order.purchase_requisition,name='purchase-requisition-list'),
    path('purchase_requisition/create/<str:document_product_id>/',purchase_order.create_purchase_order,name='new-purchase-requisition'),
    path('add_purchase_requisition/<str:purchase_requisition_id>/update/',purchase_order.add_purchase_requisition,name='update-purchase-requisition'),
    path('purchase_requisition/<str:purchase_requisition_id>/Detail/',purchase_order.view_purchase_requisition,name='purchase-requisition-detail'),
    path('approve_purchase_requisition/<str:purchase_requisition_id>/approve/',purchase_order.approve_purchase_requisition,name='approve-purchase-requisition'),
    path('cancel_purchase_requisition/<str:purchase_requisition_id>/cancel/',purchase_order.cancel_purchase_requisition,name='cancel-purchase-requisition'),
    path('complete_supplier_selection/<str:purchase_requisition_id>/confirm/',purchase_order.complete_supplier_selection,name='complete-supplier-selection'),
    path('add_quotation_requisition/<str:quotation_id>/quotation/',purchase_order.add_quotation_requisition,name='quotation-form'),
    path('approve_quotation_requisition/<str:quotation_id>/approve/',purchase_order.approve_quotation_requisition,name='approve-quotation'),
    path('reject_quotation_requisition/<str:quotation_id>/reject/',purchase_order.reject_quotation_requisition,name='reject-quotation'),

    path('lpo/<str:purchase_requisition_id>/new/',purchase_order.create_lpo,name='new-lpo'),
    path('lpo/<str:lpo_id>/detail/',purchase_order.view_lpo,name='detail-lpo'),
    path('lpo/<str:lpo_id>/approve/',purchase_order.approve_lpo,name='approve-lpo'),
    path('lpo/<str:lpo_id>/cancel/',purchase_order.cancel_lpo,name='cancel-lpo'),
    path('lpo/',purchase_order.lpo,name='lpo'),


]

django_project/purchase_order/forms.py
from django import forms
from .models import *
from django.forms.widgets import NumberInput


class PurchaseRquisitionForm(forms.ModelForm):
       
    quantity = forms.IntegerField(label=False)
    unit_price=forms.FloatField(label=False) 
    class Meta:
        model = PurchaseRequisition
        fields = ('purchase_requisition_date','quantity','unit_price')


class DecisionRquisitionForm(forms.ModelForm):
       
    reason = forms.CharField(
    widget=forms.Textarea(attrs={'maxlength': 1200}),
        label=False,required=True)
    class Meta:
        model = PurchaseRequisition_Suppliers
        fields = ('reason',)

class QoutationForm(forms.ModelForm):
    amount=forms.FloatField(label=False) 
    class Meta:
        model = PurchaseRequisition_Suppliers
        fields = ('amount',)

django_project/purchase_order/views.py
from django.shortcuts import render

# Create your views here.

django_project/templates/purchaseorder/purchase_requisition/view-purchase-requisition.html
{% extends 'partials/purchaseorder/purchasebase.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block extra_css %}
    
    <!-- DataTables -->
    <link href="{% static 'libs/datatables.net-bs4/css/dataTables.bootstrap4.min.css' %}" rel="stylesheet" type="text/css" />
    <link href="{% static 'libs/datatables.net-buttons-bs4/css/buttons.bootstrap4.min.css' %}" rel="stylesheet" type="text/css" />

    <!-- Responsive datatable examples -->
    <link href="{% static 'libs/datatables.net-responsive-bs4/css/responsive.bootstrap4.min.css' %}" rel="stylesheet" type="text/css" />  
    <link href="{% static 'libs/bootstrap-datepicker/dist/css/bootstrap-datepicker.min.css' %}" rel="stylesheet" type="text/css">
    {% comment %} <link href="{% static 'libs/select2/css/select2.min.css' %}" rel="stylesheet" type="text/css" /> {% endcomment %}
    <link href="{% static 'css/bootstrap.min.css' %}" id="bootstrap-style" rel="stylesheet" type="text/css" />
    <!-- Icons Css -->
    <link href="{% static 'css/icons.min.css' %}" rel="stylesheet" type="text/css" />
    <!-- App Css-->
    <link href="{% static 'css/app.min.css' %}" id="app-style" rel="stylesheet" type="text/css" />

{% endblock %}
{% block contents %}
<div class="row">
    <div class="col-xl-3">
        {% #card  %}
        
            
                <img  src="{% static 'images/brands/logo.png'%}" alt="" class="img-fluid">
           
            <br>
            <br>
            <h5 class="'mt-4" class="fw-semibold">Overview</h5>
            {% #table2 %}
                {% #tbody %}
                {% #tr name ="rstafid" %}
                {% #td name ="headid" %} ID :{% /td %}
                {% #td name ="restockid" %}{{purchase_requisition.id}}{% /td %}
            {% /tr  %}
            
            {% #tr name ="name" %}
                {% #td name ="headdate" %}Date :{% /td %}
                {% #td name ="username" %}{{ purchase_requisition.purchase_requisition_date }}{% /td %}
            {% /tr  %}
            {% #tr name ="name" %}
                {% #td name ="headsupplier" %}Product :{% /td %}
                {% #td name ="username" %}{{ purchase_requisition.product_id.name }}{% /td %}
            {% /tr  %}
        
            {% #tr name ="rdriver" %}
                {% #td name ="headdriver" %}Quantity :{% /td %}
                {% #td name ="userdriver" %}{{purchase_requisition.quantity }}{% /td %}
            {% /tr  %}
            {% #tr name ="rcontact" %}
                {% #td name ="headcontact" %}Total Amount :{% /td %}
                {% #td name ="contact" %}{{purchase_requisition.total_amount }}{% /td %}
            {% /tr  %}
            
            
            {% #tr name ="rstatus" %}
                {% #td name ="headstatus" %}Status :{% /td %}
                {% #td name ="userstatus" %}
                {% if purchase_requisition.status == 'Pending' %}
                    <span class="badge bg-info">{{purchase_requisition.status}}</span>
                {% elif purchase_requisition.status == 'Approved'  %}
                    <span class="badge bg-success">{{purchase_requisition.status}}</span>
                {% else %}
                    <span class="badge bg-danger">{{purchase_requisition.status}}</span>
                        
                {% endif %}
                {% /td %}
                    
            {% /tr  %}
                {% /tbody %}
            {% /table2 %}
            {% #actions name ="districtedit" %}
                {% if purchase_requisition.status == 'Pending' %}
                    <a href="#delete_link" id="delete-record" data-record-id="{{ purchase_requisition.id }}" data-bs-toggle="modal" class="delete-record btn btn-soft-success w-100" data-target="#jobDelete">Approve</a> 
                    <a href="{% url 'purchaseorder:cancel-purchase-requisition' purchase_requisition.id %}" class="btn btn-soft-danger w-100">Cancel</a>
                {% endif %}
                {% if purchase_requisition.release and not purchase_requisition.status == 'LPO Created' %}
                    <a href="{% url 'purchaseorder:new-lpo'  purchase_requisition.id %}" class="btn btn-soft-warning w-100">Create LPO</a>
                {% endif %}
                
                <a href="{% url 'purchaseorder:purchase-requisition-list' %}" class="btn btn-soft-primary w-100">Close</a>

            {% /actions %}
            
        {% /card  %}
        
    </div>
    <div class="col-xl-9">
        
         
        {% #card  %}
            <div class="row">
                <div class="col-sm-12 d-flex justify-content-end mb-4" >
                    <img src="{% static 'images/brands/logo.png'%}" alt="" class="img-fluid">
                </div>
                <br>
                <br>
            </div>
            <div class="row">
                <div class="table-responsive">
                    
                    
                    {% #table %}
                        {% #thead %}
                            {% #tr name ="headrow" %}
                                
                                {% #th name ="headid" %}Supplier {% /th %}
                                {% #th name ="headname" %}Qoutation{% /th %}
                                {% #th name ="headbrand" %}Status{% /th %}
                                {% #th name ="headdes" %}Reason{% /th %}
                                
                              
                                {% #th name ="headAction" %} Action {% /th %}
                                
                            {% /tr %}
                        {% /thead%}
                        {% #tbody %}
                            {% for data in suppliers  %}
                                {% #tr name ="bodyrow" %}
                                    
                                    {% #td name ="id" %}{{data.supplier_id.name}}{% /td %}
                                    {% #td name ="product" %}{{data.amount}}{% /td %}
                                    
                                    {% #td name ="status" %}
                                        {% if data.status == 'Selected' %}
                                            <span class="badge bg-info">{{data.status}}</span>
                                        
                                        {% else %}
                                            <span class="badge bg-danger">{{data.status}}</span>
                                                
                                        {% endif %}
                                    
                                    {% /td %}
                                    
                                    {% #td name ="des" %}{{data.reason  }}{% /td %}
                                    
                                    
                                        {% #td name ="districtaction" %}
                                            
                                            {% #actions name ="districtedit" %}
                                                  {% if purchase_requisition.status == 'Approved' %}
                                                        {% if data.status is None %}
                                                            <a href="{% url 'purchaseorder:quotation-form' data.id %}" class="btn btn-soft-primary w-100">Quotation</a>
                                                            <a href="{% url 'purchaseorder:approve-quotation' data.id %}" class="btn btn-soft-warning w-100">Approve</a>
                                                            <a href="{% url 'purchaseorder:reject-quotation' data.id %}" class="btn btn-soft-danger w-100">Reject</a>
                                                        {% endif %}
                                                  {% endif %}
                                            {% /actions %}
        
                                        {% /td %}
                                    
                                {% /tr %}
                            {% endfor %}
                        {% /tbody %}
                    {% /table %}
                    
                    <!-- end table -->
                </div>
            </div>
           
                <div class="row">
                    
                    <div class="col-3">
                        <a href="{% url 'purchaseorder:complete-supplier-selection' purchase_requisition.id %}" class="btn btn-soft-primary w-100">Comfirm Supplier Selection</a>
                    </div>

                </div>
            
                
           
        {% /card %}
                <!--end card-->
               
      
        
    </div>
    
</div>


{% endblock %}

{% block extra_content %}  
    {% #comfirmation name="approve"  %}
        {% #avatar %}
            <i class="bx bx-check-double"></i>     
        {% /avatar %} 
        {% #comfirmationtext %}
            Are you sure you want to approve this purchase Requisition
        {% /comfirmationtext %} 
        {% #comfirmation_footer %}
            <a href="#" id ="deleteModalAnchor" class="btn btn-danger">Approve Now</a>
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        {% /comfirmation_footer %}     
    {% /comfirmation %}
 
    {% #cancelcomfirmation name= "cancel"  %}
        {% #avatar %}
            <i class="mdi mdi-trash-can-outline"></i>     
        {% /avatar %} 
        {% #comfirmationtext %}
            Are you sure you want to Cancel this Purchase Requisition
        {% /comfirmationtext %} 
        {% #comfirmation_footer %}
            <a href="#" id ="deleteModalAnchor1" class="btn btn-danger">Cancel Now</a>
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        {% /comfirmation_footer %}     
    {% /cancelcomfirmation %}
 


{% endblock %}

{% block extra_javascript %}

     <!-- Required datatable js -->
     <script src="{% static 'libs/datatables.net/js/jquery.dataTables.min.js' %}"></script>
     <script src="{% static 'libs/datatables.net-bs4/js/dataTables.bootstrap4.min.js' %}"></script>
     <script src="{% static 'libs/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js' %}"></script>
     <!-- Buttons examples -->
     <script src="{% static 'libs/datatables.net-buttons/js/dataTables.buttons.min.js' %}"></script>
     <script src="{% static 'libs/datatables.net-buttons-bs4/js/buttons.bootstrap4.min.js' %}"></script>
     <script src="{% static 'libs/jszip/dist/jszip.min.js' %}"></script>
     <script src="{% static 'libs/pdfmake/build/pdfmake.min.js' %}"></script>
     <script src="{% static 'libs/pdfmake/build/vfs_fonts.js' %}"></script>
     <script src="{% static 'libs/datatables.net-buttons/js/buttons.html5.min.js' %}"></script>
     <script src="{% static 'libs/datatables.net-buttons/js/buttons.print.min.js' %}"></script>
     <script src="{% static 'libs/datatables.net-buttons/js/buttons.colVis.min.js' %}"></script>
     
     <!-- Responsive examples -->
     <script src="{% static 'libs/datatables.net-responsive/js/dataTables.responsive.min.js' %}"></script>
     <script src="{% static 'libs/datatables.net-responsive-bs4/js/responsive.bootstrap4.min.js' %}"></script>

     <!-- Datatable init js -->
     <script src="{% static 'js/pages/datatables.init.js' %}"></script>
     
    {% comment %} <script src="{% static 'js/auto_modal.js' %}"></script> {% endcomment %}

     <script>
        document.addEventListener("DOMContentLoaded", function() {
            var deleteAnchors = document.getElementsByClassName("delete-record");
            var deleteModalAnchor = document.getElementById("deleteModalAnchor");
            Array.from(deleteAnchors).forEach(function(anchor) {
              anchor.addEventListener("click", function(event) {
                event.preventDefault();
                var recordId = this.getAttribute("data-record-id"); 
                deleteModalAnchor.setAttribute("data-record-id", recordId);
                deleteModalAnchor.setAttribute("href", "/purchaseorder/approve_purchase_requisition/" + recordId + "/approve/");
                deleteModalAnchor.style.display = "block";
              });
            });
          });
          document.addEventListener("DOMContentLoaded", function() {
            var deleteAnchors = document.getElementsByClassName("delete-record1");
            var deleteModalAnchor1 = document.getElementById("deleteModalAnchor1");
            Array.from(deleteAnchors).forEach(function(anchor) {
              anchor.addEventListener("click", function(event) {
                event.preventDefault();
                var recordId = this.getAttribute("data-record-id1"); 
                deleteModalAnchor1.setAttribute("data-record-id1", recordId);
                deleteModalAnchor1.setAttribute("href", "/purchaseorder/approve_purchase_requisition/" + recordId1 + "/cancel/");
                deleteModalAnchor1.style.display = "block";
              });
            });
          });
     </script>

{% endblock %}